[build]
builder = "nixpacks"

[deploy]
region = "europe-west4"
startCommand = "python main.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
